name: Run unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libglib2.0-dev libxml2-dev libcunit1-dev libjansson-dev liblua5.3-dev valgrind
    - name: Clone apteryx
      uses: actions/checkout@v2
      with:
        repository: alliedtelesis/apteryx
        path: apteryx
    - name: Build Apteryx
      run: make -C ./apteryx
    - name: Build apteryx-xml and unit tests
      run: APTERYX_PATH=./apteryx make unittest
    - name: Run Apteryxd
      run: LD_LIBRARY_PATH=./apteryx ./apteryx/apteryxd -b
    - name: Run tests
      run: LD_LIBRARY_PATH=./apteryx:. G_SLICE=always-malloc valgrind --keep-debuginfo=yes --leak-check=full --error-exitcode=1 ./unittest
